spring:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 3s

lab:
  vector:
    redis:
      index-name: ${REDIS_VECTOR_INDEX:my_vector_index}
      vector-field: ${REDIS_VECTOR_FIELD:vec}
      content-field: ${REDIS_CONTENT_FIELD:content}
      top-k: ${REDIS_VECTOR_TOP_K:5}
      distance-metric: ${REDIS_DISTANCE_METRIC:COSINE}
